name = "AutoRisk"
uuid = "c91b7102-3640-11e9-1a5c-f77073b5ac95"
repo = "https://github.com/sisl/AutoRisk.jl.git"
version = "0.7.0"

[deps]
AutoViz = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
AutomotiveDrivingModels = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
BayesNets = "ba4760a4-c768-5bed-964b-cf806dc591cb"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Discretizers = "6e83dbb3-75ca-525b-8ae2-3751f0dd50b4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Records = "5984c134-fa48-5ed5-a57f-fc2f6936871f"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Vec = "44eeaf0b-fee4-471f-9310-ed6585cb3142"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
